name: Called workflow - Deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: AzureWebAppBB     # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

on:
  workflow_call:
    inputs:
      deployapp:
        description: 'Deploy App'
        required: true
        type: boolean
        default: false
   
  workflow_dispatch:
    inputs:
      deployapp:
        description: 'Deploy App'
        required: true
        type: boolean
        default: false
        
jobs:
  deploy_webapp:
    runs-on: ubuntu-latest
    
    steps:
        run: echo ${{ github.action_repository }}
        
      - if: github.event.inputs.deployapp == 'true'
        name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
        
      - if: github.event.inputs.deployapp == 'true'
        name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
